install:
  - choco install gitversion.portable -pre -y

nuget:
  account_feed: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build_script:
  - cmd: set PackageVersion=%GitVersion_SemVer%
  - cmd: msbuild PlaceholderFallback.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:detailed

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:

  # pushing a single file
  - path: PlaceholderFallback.Sitecore.Master\bin\Package_$(configuration)\PlaceholderFallback.update
  - path: PlaceholderFallback\bin\HedgehogDevelopment.PlaceholderFallback.*